### ISSUE TITLE
Use of Typewriter for commercial use

### ISSUE THREAD

**Issue by CQVan** [aarthificial-unity/typewriter#7]
So I'm an indie dev working on my own game and was ecstatic to see typewriter being released to the public

I'm confused if I can use it for my game because the git repo has the MIT license but the readme says released for educational purposes

Can I use this for my game

**Comment by aarthificial** [comment]
Sorry for the late response.
The project is licensed under MIT and can be used freely for commercial products.
The "educational purposes" in README refer to the project not being developed any further

**Comment by CQVan** [comment]
Thank you for the clarification Good luck on the reimagine of Astortion, from looking at the dev log it looks great alreadyOn May 15, 2024, at 2:16 AM, Jacob ***@***.***> wrote:﻿
Sorry for the late response.
The project is licensed under MIT and can be used freely for commercial products.
The "educational purposes" in README refer to the project not being developed any further

**Comment by aarthificial** [comment]
Thank you and good luck with your game too!
